# Use the official ASP.NET runtime as a base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

# Use the official .NET SDK to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy project and solution files first for caching
COPY backend/Chess.net/*.sln .
COPY backend/Chess.net/Chess.net.csproj Chess.net/
COPY backend/ChessGame/ChessGame.csproj ChessGame/
COPY backend/ApiTests/ApiTests.csproj ApiTests/
COPY backend/Domain/Domain.csproj Domain/
COPY backend/Infrastructure/Infrastructure.csproj Infrastructure/
COPY backend/IntegrationTests/IntegrationTests.csproj IntegrationTests/
COPY backend/Logic/Logic.csproj Logic/
COPY backend/LogicTests/LogicTests.csproj LogicTests/

# Restore dependencies
WORKDIR /src/Chess.net
RUN dotnet nuget locals all --clear
RUN dotnet restore

# Copy the rest of the source files
COPY backend/ .

# Build and publish the application
RUN dotnet publish Chess.net -c Release -o /app/publish

# Final stage: runtime image
FROM base AS final
WORKDIR /app

# Copy published application from build stage
COPY --from=build /app/publish .

# Copy necessary files (e.g., .txt and Stockfish .exe) to the runtime image
COPY backend/*.txt .
COPY backend/stockfish-ubuntu-x86-64 .

# Set environment variable for ASP.NET Core
ENV ASPNETCORE_URLS=http://+:5000

# Set the entry point for the application
ENTRYPOINT ["dotnet", "Chess.net.dll"]
